using generated = Teleportal.Client.Generated.generated;
using Generated = Teleportal.Client.Generated;
using RSharp;

// This file is manually implemented for now but will be autogenerated eventually

namespace Teleportal.Client.Contract.Properties.Channels
{
    using struct_RVec_Keyframe_U8 = Generated.Vec_tp_client_contract_properties_channelsKeyframeU8.__Internal;
    using struct_RVec_Keyframe_U8_ptr = Generated.Vec_tp_client_contract_properties_channelsKeyframeU8_ptr.__Internal;
    using struct_RVec_Keyframe_U8_const_ptr = Generated.Vec_tp_client_contract_properties_channelsKeyframeU8_const_ptr.__Internal;

    public sealed class RVec_Keyframe_U8 : RVec<Keyframe_U8, struct_RVec_Keyframe_U8>
    {

        // TODO: Make versions from const_ptr and ptr
        public RVec_Keyframe_U8(struct_RVec_Keyframe_U8 inner) : base(inner) { }

        override protected void NativeDrop(struct_RVec_Keyframe_U8 inner)
        {
            generated.__Internal.TpClientContractPropertiesChannelsRVecKeyframeU8Drop(inner);
        }

        public override void push(Keyframe_U8 e)
        {
            throw new System.NotImplementedException("todo");
        }

        public override Keyframe_U8 this[int index]
        {
            get => throw new System.NotImplementedException("todo");
            set => throw new System.NotImplementedException("todo");
        }
    }
}
