using ffi = tp_client.generated.__Internal;
using States = Teleportal.Client.Contract.Properties.States;
using ObjectHandle = Teleportal.Client.Object.ObjectHandle;
using RSharp;

namespace Teleportal.Client
{
    partial class Baseline
    {

        // TODO(SER-406): This should all be autogenerated
        public States.StateHandle_U8 BindStateU8(States.StateId_U8 id, ObjectHandle obj)
        {
            var p = new Ptr<States.StateHandle_U8>(ffi.TpClientBaselineBaselineBindStateU8(this.Inner.Value.p, id.Inner.Value.p, obj.Inner.Value.p));
            return new States.StateHandle_U8(p);
        }

        public States.StateHandle_I8 BindStateI8(States.StateId_I8 id, ObjectHandle obj)
        {
            var p = new Ptr<States.StateHandle_I8>(ffi.TpClientBaselineBaselineBindStateI8(this.Inner.Value.p, id.Inner.Value.p, obj.Inner.Value.p));
            return new States.StateHandle_I8(p);
        }
        public States.StateHandle_F32 BindStateF32(States.StateId_F32 id, ObjectHandle obj)
        {
            var p = new Ptr<States.StateHandle_F32>(ffi.TpClientBaselineBaselineBindStateF32(this.Inner.Value.p, id.Inner.Value.p, obj.Inner.Value.p));
            return new States.StateHandle_F32(p);
        }

    }
}
