using ffi = constellation.generated.__Internal;
using States = Teleportal.Client.Contract.Properties.States;
using ObjectHandle = Teleportal.Client.Object.ObjectHandle;
using RSharp;

namespace Teleportal.Client
{
    partial class Baseline
    {

        // TODO(SER-406): This should all be autogenerated
        public States.StateHandle_U8 BindStateU8(States.StateId_U8 id, ObjectHandle obj)
        {
            var p = new Ptr<States.StateHandle_U8>(ffi.ConstellationBaselineBaselineBindStateU8(this.Inner.Value.p, id.Inner.Value.p, obj.Inner.Value.p));
            return new States.StateHandle_U8(p);
        }

        public States.StateHandle_I8 BindStateI8(States.StateId_I8 id, ObjectHandle obj)
        {
            var p = new Ptr<States.StateHandle_I8>(ffi.ConstellationBaselineBaselineBindStateI8(this.Inner.Value.p, id.Inner.Value.p, obj.Inner.Value.p));
            return new States.StateHandle_I8(p);
        }
        public States.StateHandle_I16 BindStateI16(States.StateId_I16 id, ObjectHandle obj)
        {
            var p = new Ptr<States.StateHandle_I16>(ffi.ConstellationBaselineBaselineBindStateI16(this.Inner.Value.p, id.Inner.Value.p, obj.Inner.Value.p));
            return new States.StateHandle_I16(p);
        }
        public States.StateHandle_F32 BindStateF32(States.StateId_F32 id, ObjectHandle obj)
        {
            var p = new Ptr<States.StateHandle_F32>(ffi.ConstellationBaselineBaselineBindStateF32(this.Inner.Value.p, id.Inner.Value.p, obj.Inner.Value.p));
            return new States.StateHandle_F32(p);
        }
        public States.StateHandle_U64 BindStateU64(States.StateId_U64 id, ObjectHandle obj)
        {
            var p = new Ptr<States.StateHandle_U64>(ffi.ConstellationBaselineBaselineBindStateU64(this.Inner.Value.p, id.Inner.Value.p, obj.Inner.Value.p));
            return new States.StateHandle_U64(p);
        }
        public States.StateHandle_String BindStateString(States.StateId_String id, ObjectHandle obj)
        {
            var p = new Ptr<States.StateHandle_String>(ffi.ConstellationBaselineBaselineBindStateString(this.Inner.Value.p, id.Inner.Value.p, obj.Inner.Value.p));
            return new States.StateHandle_String(p);
        }
        public States.StateHandle_ObjectHandle BindStateObjectHandle(States.StateId_ObjectHandle id, ObjectHandle obj)
        {
            var p = new Ptr<States.StateHandle_ObjectHandle>(ffi.ConstellationBaselineBaselineBindStateObjectHandle(this.Inner.Value.p, id.Inner.Value.p, obj.Inner.Value.p));
            return new States.StateHandle_ObjectHandle(p);
        }
    }
}
