// This file is autogenerated, with one per class.

using IntPtr = System.IntPtr;
using generated = Teleportal.Client.Generated.generated;


namespace Teleportal.Client.{{namespace_super}}
{
    partial class ToManaged
    {
        public static unsafe {{namespace_sub}}.{{class_ident}} f(OwnershipSemantics ownershipSemantics, Ptr<{{namespace_sub}}.{{class_ident}}> ptr)
        {
            return new {{namespace_sub}}.{{class_ident}}(ptr, ownershipSemantics);
        }
    }
}

namespace Teleportal.Client.{{namespace_super}}.{{namespace_sub}}
{
    public sealed class {{class_ident}} : Wrapper<{{class_ident}}>
    {
        public {{class_ident}}(Ptr<{{class_ident}}> ptr, OwnershipSemantics ownershipSemantics) : base(ptr, ownershipSemantics) { }

        {{#if new_expr}}
        public unsafe {{class_ident}}({{new_args}}) : base(
            new Ptr<{{class_ident}}>({{new_expr}}),
            OwnershipSemantics.Owned
        )
        { }
        {{/if}}

        override protected void NativeDrop(Ptr<{{class_ident}}> ptr)
        {
            {{drop_ident}}(ptr.p);
        }

        {{> additional_methods}}
    }
}
